services:
  rr-localization-noetic:
    image: rr-localization-noetic:dev
    build:
      context: .
      dockerfile: Dockerfile.localization
      args:
        INSTALL_EXTRA_DEV_TOOLS: ${INSTALL_EXTRA_DEV_TOOLS:-false}
    container_name: rr-localization-noetic

    tty: true
    stdin_open: true
    command: bash

    network_mode: host
    ipc: host
    privileged: true

    environment:
      DISPLAY: ${DISPLAY}
      XAUTHORITY: /home/rr/.Xauthority
      QT_X11_NO_MITSHM: "1"
      LIBGL_ALWAYS_INDIRECT: "0"
      LIBGL_ALWAYS_SOFTWARE: "1"
      MESA_LOADER_DRIVER_OVERRIDE: "llvmpipe"
      ROS_DISTRO: noetic
      XDG_CONFIG_HOME: /home/rr/.config
      DISABLE_ROS1_EOL_WARNINGS: "1"

    user: "${DOCKER_UID:-1000}:${DOCKER_GID:-1000}"

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOST_XAUTHORITY:-${HOME}/.Xauthority}:/home/rr/.Xauthority:ro
      - /dev/dri:/dev/dri
      - ~/.ssh:/home/rr/.ssh:ro
      - ~/data:/home/rr/data:rw

      # workspace
      - ~/localizationws/src:/home/rr/catkin_ws/src:rw
      - ~/localizationws/build:/home/rr/catkin_ws/build:rw
      - ~/localizationws/devel:/home/rr/catkin_ws/devel:rw

      # git
      - ~/.gitconfig:/home/rr/.gitconfig:ro
      - ~/.git-credentials:/home/rr/.git-credentials:ro

      # persistent data
      - ~/.bash_history:/home/rr/.bash_history
      - ~/docker/logs/ros:/home/rr/.ros/log:rw
      - ~/docker/logs/app:/home/rr/logs:rw
      - ~/docker/rr_localization/.vscode-server:/home/rr/.vscode-server
      - ~/docker/rr_localization/config:/home/rr/.config:rw
      - ~/.bashrc:/home/rr/.bashrc:ro

    devices:
      - /dev/dri:/dev/dri